# Generated by Django 4.2.10 on 2024-02-08 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('office_location', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('office_location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Waiting for Check in', 'Waiting for Check in'), ('Inside Building', 'Inside Building'), ('Checked Out', 'Checked Out')], max_length=20)),
                ('visiting_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.employee')),
            ],
        ),
    ]
